CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT NOT NULL,
);

ALTER TABLE user_orders(
    ADD COLUMN 
        user_id INTEGER REFERENCES users(id)
        ON DELETE SET NULL
);